stages:
  - lint
  - selftest
  - build
  - test

selftest:
  name: selftest
  image: exakat/exakat:latest
  script:
    - exakat project -v 

build:
  stage: build
  image: php:7.3-cli-stretch
  script:
    - bash ci/docker_install.sh

test:
  stage: test
  image: php:7.3-cli-stretch
  script:
    - sh ci/docker_install.sh
    - phpunit --testsuite One


lint:
  stage: lint
  image: sixlive/php-lint-fix

  script:
    - php-cs-fixer fix --dry-run

